/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterInvestorRouteImport } from './routes/register.investor'
import { Route as RegisterBusinessRouteImport } from './routes/register.business'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as DashboardInvestorIndexRouteImport } from './routes/dashboard.investor.index'
import { Route as DashboardBusinessIndexRouteImport } from './routes/dashboard.business.index'
import { Route as DashboardInvestorPortfolioRouteImport } from './routes/dashboard.investor.portfolio'
import { Route as DashboardBusinessPaymentsRouteImport } from './routes/dashboard.business.payments'
import { Route as DashboardBusinessCreateListingRouteImport } from './routes/dashboard.business.create-listing'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterInvestorRoute = RegisterInvestorRouteImport.update({
  id: '/register/investor',
  path: '/register/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterBusinessRoute = RegisterBusinessRouteImport.update({
  id: '/register/business',
  path: '/register/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestorIndexRoute = DashboardInvestorIndexRouteImport.update({
  id: '/dashboard/investor/',
  path: '/dashboard/investor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessIndexRoute = DashboardBusinessIndexRouteImport.update({
  id: '/dashboard/business/',
  path: '/dashboard/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestorPortfolioRoute =
  DashboardInvestorPortfolioRouteImport.update({
    id: '/dashboard/investor/portfolio',
    path: '/dashboard/investor/portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardBusinessPaymentsRoute =
  DashboardBusinessPaymentsRouteImport.update({
    id: '/dashboard/business/payments',
    path: '/dashboard/business/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardBusinessCreateListingRoute =
  DashboardBusinessCreateListingRouteImport.update({
    id: '/dashboard/business/create-listing',
    path: '/dashboard/business/create-listing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/register/business': typeof RegisterBusinessRoute
  '/register/investor': typeof RegisterInvestorRoute
  '/dashboard/business/create-listing': typeof DashboardBusinessCreateListingRoute
  '/dashboard/business/payments': typeof DashboardBusinessPaymentsRoute
  '/dashboard/investor/portfolio': typeof DashboardInvestorPortfolioRoute
  '/dashboard/business/': typeof DashboardBusinessIndexRoute
  '/dashboard/investor/': typeof DashboardInvestorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/register/business': typeof RegisterBusinessRoute
  '/register/investor': typeof RegisterInvestorRoute
  '/dashboard/business/create-listing': typeof DashboardBusinessCreateListingRoute
  '/dashboard/business/payments': typeof DashboardBusinessPaymentsRoute
  '/dashboard/investor/portfolio': typeof DashboardInvestorPortfolioRoute
  '/dashboard/business': typeof DashboardBusinessIndexRoute
  '/dashboard/investor': typeof DashboardInvestorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/register/business': typeof RegisterBusinessRoute
  '/register/investor': typeof RegisterInvestorRoute
  '/dashboard/business/create-listing': typeof DashboardBusinessCreateListingRoute
  '/dashboard/business/payments': typeof DashboardBusinessPaymentsRoute
  '/dashboard/investor/portfolio': typeof DashboardInvestorPortfolioRoute
  '/dashboard/business/': typeof DashboardBusinessIndexRoute
  '/dashboard/investor/': typeof DashboardInvestorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/listings/$id'
    | '/register/business'
    | '/register/investor'
    | '/dashboard/business/create-listing'
    | '/dashboard/business/payments'
    | '/dashboard/investor/portfolio'
    | '/dashboard/business/'
    | '/dashboard/investor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/listings/$id'
    | '/register/business'
    | '/register/investor'
    | '/dashboard/business/create-listing'
    | '/dashboard/business/payments'
    | '/dashboard/investor/portfolio'
    | '/dashboard/business'
    | '/dashboard/investor'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/listings/$id'
    | '/register/business'
    | '/register/investor'
    | '/dashboard/business/create-listing'
    | '/dashboard/business/payments'
    | '/dashboard/investor/portfolio'
    | '/dashboard/business/'
    | '/dashboard/investor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRoute
  ListingsIdRoute: typeof ListingsIdRoute
  RegisterBusinessRoute: typeof RegisterBusinessRoute
  RegisterInvestorRoute: typeof RegisterInvestorRoute
  DashboardBusinessCreateListingRoute: typeof DashboardBusinessCreateListingRoute
  DashboardBusinessPaymentsRoute: typeof DashboardBusinessPaymentsRoute
  DashboardInvestorPortfolioRoute: typeof DashboardInvestorPortfolioRoute
  DashboardBusinessIndexRoute: typeof DashboardBusinessIndexRoute
  DashboardInvestorIndexRoute: typeof DashboardInvestorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/investor': {
      id: '/register/investor'
      path: '/register/investor'
      fullPath: '/register/investor'
      preLoaderRoute: typeof RegisterInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/business': {
      id: '/register/business'
      path: '/register/business'
      fullPath: '/register/business'
      preLoaderRoute: typeof RegisterBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/investor/': {
      id: '/dashboard/investor/'
      path: '/dashboard/investor'
      fullPath: '/dashboard/investor/'
      preLoaderRoute: typeof DashboardInvestorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business/': {
      id: '/dashboard/business/'
      path: '/dashboard/business'
      fullPath: '/dashboard/business/'
      preLoaderRoute: typeof DashboardBusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/investor/portfolio': {
      id: '/dashboard/investor/portfolio'
      path: '/dashboard/investor/portfolio'
      fullPath: '/dashboard/investor/portfolio'
      preLoaderRoute: typeof DashboardInvestorPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business/payments': {
      id: '/dashboard/business/payments'
      path: '/dashboard/business/payments'
      fullPath: '/dashboard/business/payments'
      preLoaderRoute: typeof DashboardBusinessPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business/create-listing': {
      id: '/dashboard/business/create-listing'
      path: '/dashboard/business/create-listing'
      fullPath: '/dashboard/business/create-listing'
      preLoaderRoute: typeof DashboardBusinessCreateListingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRoute,
  ListingsIdRoute: ListingsIdRoute,
  RegisterBusinessRoute: RegisterBusinessRoute,
  RegisterInvestorRoute: RegisterInvestorRoute,
  DashboardBusinessCreateListingRoute: DashboardBusinessCreateListingRoute,
  DashboardBusinessPaymentsRoute: DashboardBusinessPaymentsRoute,
  DashboardInvestorPortfolioRoute: DashboardInvestorPortfolioRoute,
  DashboardBusinessIndexRoute: DashboardBusinessIndexRoute,
  DashboardInvestorIndexRoute: DashboardInvestorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
